#!/bin/bash
# Writes DHCP lease information into the cloud-init data directory.
# This file is sourced by dhclient so do not prepend 'exec' to the
# following.

python -m cloudinit.cmd.dhclient_hook

